---
deployment:
 tasks:
  - export DEPLOYPATH=/home/christian/sandbox.cleberg.io/
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp -R binarytodecimal $DEPLOYPATH
  - /bin/cp -R localstorage $DEPLOYPATH
  - /bin/cp -R currencyconverter $DEPLOYPATH